name: API Tests • Allure Report • Pages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

# Default to read
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    name: Run tests (continue on failures)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e ".[dev]" || true; fi

      - name: Run pytest (produce Allure results)
        id: pytest
        continue-on-error: true
        run: |
          mkdir -p allure-results
          pytest -n auto -m "not e2e" \
            --alluredir=allure-results \
            --junitxml=reports/junit.xml || exit_code=$?
          echo "exit_code=${exit_code:-0}" >> "$GITHUB_OUTPUT"
          if [ "${exit_code:-0}" -ne 0 ]; then
            echo "Some tests failed" >> $GITHUB_STEP_SUMMARY
          else
            echo "All tests passed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Allure raw results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: warn

      - name: Upload JUnit & HTML reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            reports/**
          if-no-files-found: ignore

  build_allure:
    name: Build Allure report (fails if report generation fails)
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure raw results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Build Allure report with history
        id: allure
        uses: simple-elf/allure-report-action@v1.13
        with:
          allure_results: ./allure-results
          allure_report: ./allure-report
          allure_history: ./allure-history

      - name: Upload built report (debug artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-built
          path: |
            ./allure-report/**
            ./allure-history/**
          if-no-files-found: error

  deploy_pages:
    name: Publish Allure to GitHub Pages
    needs: build_allure
    if: ${{ always() }}
    runs-on: ubuntu-latest
    # Only this job needs write to contents for gh-pages pushes
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download built report
        uses: actions/download-artifact@v4
        with:
          name: allure-report-built
          path: ./
      
      - name: Find latest report subfolder
        id: latest
        run: |
          latest=$(ls -d */ | grep -E '^[0-9]+/$' | sed 's#/##' | sort -n | tail -1)
          echo "latest_folder=$latest" >> $GITHUB_OUTPUT

      - name: Create root index.html that redirects to latest report
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=${{ steps.latest.outputs.latest_folder }}/">
              <title>Redirecting to the latest Allure report...</title>
            </head>
            <body>
              <p>Redirecting to the latest Allure report...</p>
              <a href="${{ steps.latest.outputs.latest_folder }}/">Click here if you are not redirected.</a>
            </body>
          </html>
          EOF
      
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history
          commit_message: "docs: update Allure report for ${{ github.sha }}"
